### ISSUE TITLE
Morning section code review

### ISSUE THREAD

**Issue by Ibizugbe** [Ibizugbe/My-Portfolio#6]
A code review was performed by my morning section team, indicating areas where possible changes could be added.

**Comment by piesieomane** [comment]
Great Job done, @Ibizugbe  you can as well remove a few animations from your code to make it classic and clean

**Comment by Said-laasri** [comment]
Hi @Ibizugbe, kindly add the contribution name and social to the README file .your code looks Good!

**Comment by Lizdev-05** [comment]
Hy @Ibizugbe , you have done really well. Do well to implement the reviews given by everyone. I wish you all the best.

**Comment by Ibizugbe** [comment]
Thanks a lot, guys, I will consider these thoughts.
